# Generated by Django 5.2.16 on 2026-07-26 23:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('language', models.CharField(default='pt-BR', max_length=20, verbose_name='idioma')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'voz',
                'verbose_name_plural': 'vozes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('source_type', models.CharField(choices=[('text', 'Texto colado'), ('pdf', 'PDF'), ('docx', 'Word'), ('epub', 'EPUB'), ('txt', 'TXT')], default='text', max_length=10, verbose_name='origem')),
                ('original_file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='arquivo original')),
                ('extracted_text', models.TextField(verbose_name='texto extraído')),
                ('speed', models.PositiveSmallIntegerField(default=170, help_text='Palavras por minuto.', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(320)], verbose_name='velocidade')),
                ('status', models.CharField(choices=[('pending', 'Na fila'), ('processing', 'Gerando áudio'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='status')),
                ('audio_file', models.FileField(blank=True, upload_to='audio/%Y/%m/', verbose_name='áudio')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='caracteres')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='duração em segundos')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='reader.voice', verbose_name='voz')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.FloatField(default=0)),
                ('char_offset', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='reader.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progresso de leitura',
                'verbose_name_plural': 'progressos de leitura',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('start_char', models.PositiveIntegerField(default=0)),
                ('end_char', models.PositiveIntegerField(default=0)),
                ('start_seconds', models.FloatField(default=0)),
                ('end_seconds', models.FloatField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='reader.document')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('document', 'order'), name='unique_document_segment_order')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status'], name='reader_docu_owner_i_30eff9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-created_at'], name='reader_docu_owner_i_86bb85_idx'),
        ),
    ]
