# Generated by Django 5.2.16 on 2026-07-30 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_azure_speech_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('max_files_per_user', models.PositiveSmallIntegerField(default=10, verbose_name='arquivos por usuário')),
                ('max_readings_per_user_month', models.PositiveSmallIntegerField(default=10, verbose_name='leituras por usuário/mês')),
                ('max_document_size_mb', models.PositiveSmallIntegerField(default=20, verbose_name='tamanho máximo de documento (MB)')),
                ('max_book_size_mb', models.PositiveSmallIntegerField(default=20, verbose_name='tamanho máximo de livro (MB)')),
                ('book_part_characters', models.PositiveIntegerField(default=100000, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(500000)], verbose_name='caracteres por parte interna')),
                ('tts_provider', models.CharField(choices=[('auto', 'Automático pelo ambiente'), ('kokoro', 'Kokoro local'), ('azure', 'Azure Speech')], default='auto', max_length=20, verbose_name='provedor de voz')),
                ('azure_speech_region', models.CharField(blank=True, default='brazilsouth', max_length=80, verbose_name='região do Azure Speech')),
                ('azure_speech_key_encrypted', models.TextField(blank=True, editable=False)),
                ('ai_provider', models.CharField(choices=[('disabled', 'Desativado'), ('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI')], default='disabled', max_length=20, verbose_name='provedor de IA')),
                ('openai_model', models.CharField(default='gpt-5.6-luna', max_length=80, verbose_name='modelo OpenAI')),
                ('openai_api_key_encrypted', models.TextField(blank=True, editable=False)),
                ('azure_openai_endpoint', models.URLField(blank=True, max_length=300, verbose_name='endpoint Azure OpenAI')),
                ('azure_openai_deployment', models.CharField(blank=True, max_length=100, verbose_name='implantação/modelo Azure OpenAI')),
                ('azure_openai_api_key_encrypted', models.TextField(blank=True, editable=False)),
                ('ai_max_input_characters', models.PositiveIntegerField(default=500000, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(2000000)], verbose_name='máximo de caracteres por operação de IA')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração da aplicação',
                'verbose_name_plural': 'configuração da aplicação',
            },
        ),
        migrations.CreateModel(
            name='AudioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=20)),
                ('voice_code', models.CharField(max_length=80)),
                ('speed', models.PositiveSmallIntegerField()),
                ('audio_file', models.FileField(upload_to='audio/cache/%Y/%m/')),
                ('duration_seconds', models.FloatField(default=0)),
                ('word_timings', models.JSONField(blank=True, default=list)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'áudio em cache',
                'verbose_name_plural': 'áudios em cache',
            },
        ),
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('readings', models.PositiveIntegerField(default=0)),
                ('synthesized_characters', models.PositiveBigIntegerField(default=0)),
                ('ai_requests', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'uso mensal',
                'verbose_name_plural': 'usos mensais',
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='book_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ordem no livro'),
        ),
        migrations.AddField(
            model_name='document',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='página final'),
        ),
        migrations.AddField(
            model_name='document',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='página inicial'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('original_file', models.FileField(upload_to='books/%Y/%m/', verbose_name='arquivo original')),
                ('source_type', models.CharField(default='pdf', max_length=10, verbose_name='formato')),
                ('speed', models.PositiveSmallIntegerField(default=170, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(320)], verbose_name='velocidade')),
                ('reading_mode', models.CharField(choices=[('academic', 'Leitura acadêmica'), ('natural', 'Leitura natural'), ('literal', 'Leitura literal')], default='academic', max_length=20, verbose_name='modo de leitura')),
                ('status', models.CharField(choices=[('processing', 'Preparando'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='processing', max_length=20, verbose_name='status')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='páginas')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='caracteres')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='reader.voice', verbose_name='voz')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('summary', 'Resumo'), ('translation', 'Tradução')], max_length=20)),
                ('target_language', models.CharField(blank=True, max_length=60)),
                ('input_hash', models.CharField(max_length=64)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Na fila'), ('processing', 'Processando'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='reader.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='reader.book')),
            ],
            options={
                'verbose_name': 'resultado de IA',
                'verbose_name_plural': 'resultados de IA',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='reader.book', verbose_name='livro'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['book', 'book_order'], name='reader_docu_book_id_bd9348_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('book', 'book_order'), name='unique_book_part_order'),
        ),
        migrations.AddField(
            model_name='monthlyusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['owner', '-created_at'], name='reader_book_owner_i_eb0800_idx'),
        ),
        migrations.AddIndex(
            model_name='airesult',
            index=models.Index(fields=['owner', 'operation', '-created_at'], name='reader_aire_owner_i_08c6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='airesult',
            index=models.Index(fields=['input_hash', 'operation'], name='reader_aire_input_h_4120a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyusage',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_user_monthly_usage'),
        ),
    ]
