# Generated by Django 5.2.16 on 2026-07-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_appconfiguration_audiocache_monthlyusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='max_files_per_user_day',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='novos arquivos por usuário/dia'),
        ),
    ]
