# Generated by Django 5.2 on 2026-07-30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0006_appconfiguration_max_files_per_user_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconfiguration",
            name="book_part_pages",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text=(
                    "Limite adicional para que o navegador nunca precise abrir "
                    "uma parte muito grande do PDF."
                ),
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(50),
                ],
                verbose_name="páginas por parte de PDF",
            ),
        ),
    ]
